linters:
    Indentation:
        enabled: true
        allow_non_nested_indentation: false
        character: space # or 'tab'
        width: 3
    Compass::*:
        enabled: true
    VendorPrefix:
            enabled: false
    FinalNewline:
        enabled: false